version: "3"
services:
  mysql_cursos:
    container_name: mysql_cursos
    hostname: mysql_cursos
    image: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - D:\YASMIN\Estudos_repo\Estudos\BancosDeDados\Curso De SQL Com MySQL - Otavio Miranda\SQL-E-KNEX:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
